### ISSUE TITLE
Find way to measure RAM/DRAM Power Usage

### ISSUE THREAD

**Issue by francsir** [DanielMadaghjian/Sustainable-Software-Project#24]
Measuring RAM/DRAM is very difficult, as there is no (or very rarely) power monitors on them. Research need to be done to find a way to estimate this power draw, more than likely some conversion between RAM size, and Usage will give us something close. 

- [x] Find a way to convert RAM Usage into an estimated Power Draw
- [x] Implement the code
- [x] Merge the code

**Comment by condrond** [comment]
DRAM usage calculated using values found on CPU sensors.
Estimation code (commented out) included for devices without the necessary DRAM sensor, but not yet implemented.
