### ISSUE TITLE
Cross check power meter

### ISSUE THREAD

**Issue by DanielMadaghjian** [DanielMadaghjian/Sustainable-Software-Project#31]
## Action
Cross check the results we gather from the backend, against a power meter, and illustrate our findings on the frontend.

**Comment by condrond** [comment]
Variance between the power meter and our software appears to be anywhere between 15w and 30w, depending on variable conditions related to the current load on the hardware. 

Constant power likely caused by screen and storage device.
Variable caused by current fan usage
